"""Stages B/C: decide *what* to read deeply, and *which parts* of it.

The premise: an LLM reading 400 files shallowly learns less about you than one
reading 40 files properly. So we spend deterministic effort on ranking, then
spend model tokens only where the density of career evidence is high.

Three ideas do the work:

* **Signal scoring.** A postmortem you wrote and rewrote eleven times is worth
  a hundred config files. Scores combine artifact class, your ownership share,
  churn, and the density of decision/impact language (Chinese and English).
* **Stratified budget.** Straight top-N lets one loud repo eat the whole
  budget and produces a lopsided portrait. Quotas per repo and per artifact
  class keep the sample representative.
* **Structural excerpting.** Long files are not truncated at N chars -- they
  are reduced to the parts that carry decisions: headings, signatures,
  comment blocks, and the neighbourhood of every decision/impact marker.
  Elisions are marked so the model knows it is seeing a reduction.
"""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass, field
from pathlib import Path

from .ingest import Document

# -- artifact classes -------------------------------------------------------
CLASS_PATTERNS: list[tuple[str, re.Pattern, float]] = [
    ("decision_record", re.compile(r"(^|/)(adr|rfc|design[_\- ]?docs?|proposals?)/"
                                   r"|\b(adr|rfc)[-_ ]?\d+", re.I), 3.0),
    ("postmortem", re.compile(r"postmortem|post-mortem|incident|复盘|事故|故障", re.I), 3.0),
    ("report", re.compile(r"report|analysis|研究|报告|方案|总结|白皮书|\.(pdf|docx)$", re.I), 2.6),
    ("readme", re.compile(r"(^|/)(readme|architecture|overview|design|contributing)"
                          r"(\.[a-z]+)?$", re.I), 2.4),
    ("spec", re.compile(r"(^|/)(docs?|spec|specs|wiki|notes)/", re.I), 1.8),
    ("changelog", re.compile(r"(^|/)(changelog|history|releases?)(\.[a-z]+)?$", re.I), 1.6),
    ("slides", re.compile(r"\.pptx$", re.I), 1.5),
    ("notebook", re.compile(r"\.ipynb$", re.I), 1.4),
    # Order matters: the narrow rules must win over the generic extension
    # rule, or every test file scores as production source.
    ("test", re.compile(r"(^|/)(tests?|spec|__tests__)/|(^|/)test_[^/]+$|[._-]test\.[a-z]+$", re.I), 0.5),
    ("infra", re.compile(r"dockerfile|\.tf$|k8s|helm|\.github/workflows/", re.I), 0.9),
    ("source", re.compile(r"\.(py|go|rs|ts|tsx|js|jsx|java|kt|scala|c|cc|cpp|rb|php|swift|ex)$", re.I), 1.0),
    ("config", re.compile(r"\.(json|ya?ml|toml|ini|cfg|xml)$", re.I), 0.35),
]

# Language of judgement -- the sentences where someone explains a choice.
DECISION_MARKERS = re.compile(
    r"\b(because|therefore|trade[- ]?off|instead of|rather than|we chose|we decided|"
    r"decision|rationale|alternative|rejected|considered|root cause|lesson|retrospect|"
    r"regret|mistake|limitation|caveat|constraint|assumption|risk|migrat|deprecat|refactor)\b"
    r"|(?:因为|所以|权衡|取舍|决定|选择了|放弃了|方案|对比|评估|瓶颈|踩坑|回滚|复盘|教训|"
    r"根因|局限|约束|假设|风险|迁移|重构|下线|折中|代价)", re.I)

# Quantified outcomes -- the difference between "optimised it" and evidence.
IMPACT_MARKERS = re.compile(
    r"(?<![\w.])\d[\d,.]*\s?(?:%|ms|s\b|us\b|qps|tps|rps|req/s|x\b|倍|万|亿|k\b|m\b|gb|mb|tb|"
    r"人天|人月|天|小时)"
    r"|\b(?:reduced|improved|increased|decreased|cut|saved|latency|throughput|p99|p95|"
    r"slo|sla|uptime|conversion|revenue|cost)\b"
    r"|(?:降低|提升|提高|减少|节省|收益|转化|成本|耗时|吞吐|稳定性|可用性)", re.I)

# Structure worth keeping verbatim when excerpting.
STRUCTURE_LINE = re.compile(
    r"^\s{0,8}(?:#{1,4}\s|\d+\.\s+\S|[-*]\s+\*\*)"                      # md headings / bold bullets
    r"|^\s{0,8}(?:def |class |func |fn |type |interface |struct |impl |"
    r"public |private |protected |async def |export (?:default |const |function )?)"
    r"|^\s{0,8}(?:@|#\[)"                                                # decorators / attributes
    r"|^\s{0,8}(?:TODO|FIXME|NOTE|HACK|XXX|WHY)\b")

BOILERPLATE = re.compile(
    r"^(?:copyright|licensed under|all rights reserved|generated by|do not edit|"
    r"autogenerated|@generated)", re.I)


def estimate_tokens(text: str) -> int:
    """Rough but stable: CJK is ~1.5 chars/token, ASCII ~4."""
    cjk = sum(1 for ch in text if "一" <= ch <= "鿿")
    return int(cjk / 1.5 + (len(text) - cjk) / 4) + 1


CHAT_MARKER = re.compile(r"<!--\s*source_type=chat\b")
CHAT_META = re.compile(r"(\w+)=([\w./-]+)")
HUMAN_TURN = re.compile(r"^## you(?: ·.*)?$", re.M)


def is_chat(text: str) -> bool:
    return bool(CHAT_MARKER.search(text[:400]))


def chat_meta(text: str) -> dict:
    """Read the metrics the connector already computed, from the staged header."""
    head = text[:800]
    m = CHAT_MARKER.search(head)
    if not m:
        return {}
    block = head[m.start():head.find("-->", m.start())]
    out: dict[str, str | int] = {}
    for key, value in CHAT_META.findall(block):
        out[key] = int(value) if value.isdigit() else value
    return out


def human_turns(text: str) -> str:
    """Only what the person actually typed.

    Scoring a transcript as a whole would mostly score the assistant's prose,
    which says nothing about the person. The same applies to evidence: the
    model's words in a session are never evidence about its user.
    """
    parts, spans = [], [m.start() for m in HUMAN_TURN.finditer(text)]
    for start in spans:
        body = text[text.index("\n", start) + 1:]
        nxt = re.search(r"^## ", body, re.M)
        parts.append(body[:nxt.start()] if nxt else body)
    return "\n".join(parts)


def classify(doc: Document) -> tuple[str, float]:
    if doc.source_type == "chat":
        return "chat_session", 2.2
    path = doc.path.replace("\\", "/")
    for name, pattern, weight in CLASS_PATTERNS:
        if pattern.search(path):
            return name, weight
    return "other", 0.8


@dataclass
class Scored:
    doc_id: str
    path: str
    repo: str | None
    artifact_class: str
    score: float
    est_tokens: int
    source_type: str = "file"
    reasons: list[str] = field(default_factory=list)
    selected: bool = False
    excerpt_strategy: str = "full"


def score_chat(doc: Document, text: str) -> Scored:
    """Chat transcripts need their own scorer.

    Decision-marker density -- the signal that works for documents -- mostly
    measures the assistant here. What distinguishes a session worth reading is
    how much of *you* is in it: long turns, sustained threads, and above all
    pushback. You cannot argue with a model about a domain you do not know,
    so correction density is the cheapest competence signal in the corpus.
    """
    meta = chat_meta(text)
    mine = human_turns(text)
    reasons = ["class=chat_session(x2.2)"]
    score = 2.2

    # Weighted length keeps the scorer language-neutral (see the connector).
    chars = int(meta.get("human_weight") or meta.get("human_chars") or len(mine))
    turns = int(meta.get("human_turns") or 1)
    pushback = int(meta.get("pushback") or len(DECISION_MARKERS.findall(mine)))
    teaching = int(meta.get("teaching") or 0)

    for label, shown, value, weight, cap in (
            ("pushback", pushback, pushback, 0.30, 2.0),
            ("teaching", teaching, teaching, 0.25, 1.5),
            ("depth", turns, turns, 0.15, 1.0),
            ("your_words", chars, chars / 1000, 0.60, 2.0)):
        if value > 0:
            bump = min(cap, value * weight)
            score += bump
            reasons.append(f"{label}={shown}(+{bump:.2f})")

    decisions = len(DECISION_MARKERS.findall(mine))
    if decisions:
        bump = min(1.5, decisions * 0.2)
        score += bump
        reasons.append(f"decisions={decisions}(+{bump:.2f})")

    if chars < 500 and int(meta.get("tool_calls") or 0) > 40:
        score -= 1.0
        reasons.append("watched-not-worked(-1.00)")

    return Scored(doc_id=doc.id, path=doc.path, repo=meta.get("repo") or doc.repo,
                  artifact_class="chat_session", score=round(score, 3),
                  est_tokens=estimate_tokens(text), source_type="chat", reasons=reasons)


def score_document(doc: Document, text: str) -> Scored:
    if doc.source_type == "chat" or is_chat(text):
        return score_chat(doc, text)
    cls, base = classify(doc)
    reasons = [f"class={cls}(x{base})"]
    score = base

    n_lines = max(text.count("\n"), 1)
    decisions = len(DECISION_MARKERS.findall(text))
    impacts = len(IMPACT_MARKERS.findall(text))
    d_density = decisions / n_lines * 100
    i_density = impacts / n_lines * 100

    if decisions:
        bump = min(2.5, d_density * 0.5)
        score += bump
        reasons.append(f"decisions={decisions}(+{bump:.2f})")
    if impacts:
        bump = min(2.0, i_density * 0.4)
        score += bump
        reasons.append(f"impact={impacts}(+{bump:.2f})")

    if doc.my_line_share is not None:
        bump = doc.my_line_share * 2.0
        score += bump
        reasons.append(f"ownership={doc.my_line_share:.2f}(+{bump:.2f})")
    elif doc.authored_by_me is False:
        score -= 1.0
        reasons.append("not-my-code(-1.00)")

    if doc.commits > 1:
        bump = min(1.5, 0.4 * (doc.commits ** 0.5))
        score += bump
        reasons.append(f"churn={doc.commits}(+{bump:.2f})")

    head = "\n".join(text.splitlines()[:5])
    if BOILERPLATE.search(head):
        score -= 0.8
        reasons.append("boilerplate-header(-0.80)")
    if n_lines < 8 and cls not in ("readme", "decision_record"):
        score -= 0.6
        reasons.append("stub(-0.60)")

    return Scored(doc_id=doc.id, path=doc.path, repo=doc.repo, artifact_class=cls,
                  score=round(score, 3), est_tokens=estimate_tokens(text),
                  source_type=doc.source_type, reasons=reasons)


# -- structural excerpting --------------------------------------------------
def excerpt(text: str, budget_tokens: int, context: int = 2) -> tuple[str, str]:
    """Reduce ``text`` to its load-bearing lines. Returns (text, strategy)."""
    if estimate_tokens(text) <= budget_tokens:
        return text, "full"
    if is_chat(text):
        return _excerpt_chat(text, budget_tokens)

    lines = text.splitlines()
    keep: set[int] = set(range(min(12, len(lines))))          # the opening always matters
    for i, line in enumerate(lines):
        if STRUCTURE_LINE.search(line) or DECISION_MARKERS.search(line) or IMPACT_MARKERS.search(line):
            keep.update(range(max(0, i - context), min(len(lines), i + context + 1)))

    # If that is still too much, keep the densest lines first.
    def line_weight(i: int) -> float:
        ln = lines[i]
        return (2.0 * bool(DECISION_MARKERS.search(ln)) + 1.5 * bool(IMPACT_MARKERS.search(ln))
                + 1.0 * bool(STRUCTURE_LINE.search(ln)) + 0.001 * (len(lines) - i))

    ordered = sorted(keep, key=line_weight, reverse=True)
    chosen: set[int] = set()
    used = 0
    for i in ordered:
        t = estimate_tokens(lines[i]) + 1
        if used + t > budget_tokens:
            continue
        chosen.add(i)
        used += t

    # A one-line gap costs more to announce than to keep.
    for i in sorted(chosen):
        if i + 2 in chosen and i + 1 not in chosen:
            chosen.add(i + 1)

    out, gap = [], 0
    for i, line in enumerate(lines):
        if i in chosen:
            if gap:
                out.append(f"      ... [{gap} lines elided] ...")
                gap = 0
            out.append(line)
        else:
            gap += 1
    if gap:
        out.append(f"      ... [{gap} lines elided] ...")
    return "\n".join(out), "structural"


def _excerpt_chat(text: str, budget_tokens: int) -> tuple[str, str]:
    """Never truncate a human turn; spend the whole budget on them.

    Assistant stubs go first, and if the person's own turns still overflow,
    the longest ones win -- a long turn is where someone explains themselves.
    """
    # Everything before the first human turn is preamble: the title and the
    # connector's metrics block. Cutting at the first "-->" would keep only
    # the title comment and silently drop pushback/human_weight -- the very
    # fields the reading contract tells the model to check.
    first = HUMAN_TURN.search(text)
    header = text[:first.start()].rstrip() if first else ""
    used = estimate_tokens(header)
    blocks: list[tuple[int, str]] = []
    for m in HUMAN_TURN.finditer(text):
        body = text[m.start():]
        nxt = re.search(r"^## ", body[1:], re.M)
        chunk = body[:nxt.start() + 1] if nxt else body
        blocks.append((estimate_tokens(chunk), chunk.rstrip()))

    keep, dropped = [], 0
    for cost, chunk in sorted(blocks, key=lambda b: -b[0]):
        if used + cost > budget_tokens:
            dropped += 1
            continue
        used += cost
        keep.append(chunk)
    order = {chunk: i for i, (_, chunk) in enumerate(blocks)}
    keep.sort(key=lambda c: order.get(c, 0))
    note = (f"\n\n<!-- assistant turns removed; {dropped} shorter human turn(s) "
            f"dropped to fit budget -->") if dropped else "\n\n<!-- assistant turns removed -->"
    return header + note + "\n" + "\n\n".join(keep), "chat-human-only"


# -- budgeted, stratified selection ----------------------------------------
def select(scored: list[Scored], budget_tokens: int, per_repo_share: float = 0.4,
           per_class_share: float = 0.45, excerpt_cap: int = 3000,
           per_source_share: float = 0.35) -> list[Scored]:
    """Greedy by score, held back by diversity quotas.

    ``per_repo_share`` caps how much of the budget any single repository may
    consume; ``per_class_share`` does the same per artifact class. Without
    these, a monorepo with 300 markdown files silently becomes your entire
    professional identity.

    ``per_source_share`` is the same argument one level up, and it is the one
    that matters once connectors are in play: a year of chat logs outweighs
    every repository put together by sheer volume, and without a cap the
    portrait becomes "a person who talks to AI a lot".
    """
    scored = sorted(scored, key=lambda s: s.score, reverse=True)
    repo_cap = budget_tokens * per_repo_share
    class_cap = budget_tokens * per_class_share
    # A quota only makes sense when there is something to balance against.
    multi_repo = len({s.repo or "_loose" for s in scored}) > 1
    multi_class = len({s.artifact_class for s in scored}) > 1
    multi_source = len({s.source_type for s in scored}) > 1
    source_cap = budget_tokens * per_source_share
    by_source: dict[str, float] = {}
    used = 0.0
    by_repo: dict[str, float] = {}
    by_class: dict[str, float] = {}

    def cost_of(s: Scored) -> int:
        return min(s.est_tokens, excerpt_cap)

    for s in scored:
        cost = cost_of(s)
        if used + cost > budget_tokens:
            continue
        rk, ck = s.repo or "_loose", s.artifact_class
        if multi_repo and by_repo.get(rk, 0) + cost > repo_cap:
            s.reasons.append("skipped:repo-quota")
            continue
        if multi_class and by_class.get(ck, 0) + cost > class_cap:
            s.reasons.append("skipped:class-quota")
            continue
        sk = s.source_type
        if multi_source and by_source.get(sk, 0) + cost > source_cap:
            s.reasons.append("skipped:source-quota")
            continue
        s.selected = True
        used += cost
        by_repo[rk] = by_repo.get(rk, 0) + cost
        by_class[ck] = by_class.get(ck, 0) + cost
        by_source[sk] = by_source.get(sk, 0) + cost

    # Quotas can leave budget on the table. Spend the remainder greedily --
    # by now every under-represented source has already had its chance.
    for s in scored:
        if s.selected:
            continue
        cost = cost_of(s)
        if used + cost > budget_tokens:
            continue
        s.selected = True
        s.reasons.append("filled:leftover-budget")
        used += cost

    for s in scored:
        if s.selected:
            s.excerpt_strategy = "full" if s.est_tokens <= excerpt_cap else "structural"
    return scored


def summarise(scored: list[Scored], excerpt_cap: int = 3000) -> dict:
    sel = [s for s in scored if s.selected]
    by_class: dict[str, int] = {}
    for s in sel:
        by_class[s.artifact_class] = by_class.get(s.artifact_class, 0) + 1
    by_source: dict[str, int] = {}
    for s in sel:
        by_source[s.source_type] = by_source.get(s.source_type, 0) + 1
    return {
        "candidates": len(scored),
        "by_source": dict(sorted(by_source.items(), key=lambda kv: -kv[1])),
        "selected": len(sel),
        "selected_tokens": sum(min(s.est_tokens, excerpt_cap) for s in sel),
        "candidate_tokens": sum(s.est_tokens for s in scored),
        "by_class": dict(sorted(by_class.items(), key=lambda kv: -kv[1])),
        "repos": sorted({s.repo for s in sel if s.repo}),
    }


def to_jsonl(scored: list[Scored], path: Path) -> None:
    import json
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        for s in scored:
            fh.write(json.dumps(asdict(s), ensure_ascii=False) + "\n")
